extends: stylelint-config-standard-scss
plugins:
  - stylelint-scss
  - stylelint-order
rules:
  # scss/at-import-no-partial-leading-underscore: null
  declaration-block-no-redundant-longhand-properties: null # We prefer longhand properties for clarity in SCSS
  selector-class-pattern: "" # We're not too strict about selector class pattern
  declaration-empty-line-before: never # No need for empty line before declaration
  order/properties-alphabetical-order: true # We're following alphabetical order in properties
  custom-property-pattern: "^([a-z][a-z0-9]*)(--?[a-z0-9]+)*$" # kebab-case pattern with allowed bem-like double --
  max-nesting-depth: 4 # We're not using normal nesting rule of 3, as admin theme is all about overriding styles
overrides:
  - files:
      - '**/ckeditor.scss'
      - '**/styles.scss'
    rules:
      scss/at-import-no-partial-leading-underscore: null
