<?php

/**
 * @file
 * Admin tools.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\locale\SourceString;

/**
 * Implements hook_toolbar_alter()
 */
function hdbt_admin_tools_toolbar_alter(&$items) {
  foreach ($items as $key => $value) {
    if (isset($items[$key]['#attached']) && is_array($items[$key]['#attached']['library'])) {
      $items[$key]['#attached']['library'][] = 'hdbt_admin_tools/hdbt_admin_tools';
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alter config translation edit form.
 */
function hdbt_admin_tools_form_config_translation_form_alter(&$form, &$form_state, $form_id) {
  if (in_array($form_id, [
    'config_translation_add_form',
    'config_translation_edit_form'
  ])) {
    $settings = &$form['config_names']['hdbt_admin_tools.site_settings'];

    // Don't translate global fields.
    $settings['footer_settings']['footer_top_content']['#open'] = TRUE;
    $settings['footer_settings']['footer_color']['#disabled'] = TRUE;
    $settings['koro_settings']['koro']['#disabled'] = TRUE;

    // Custom submit callback to invalidate caches.
    $form['#submit'][] = '_hdbt_admin_tools_config_translation_form_submit';
  }
}

function _hdbt_admin_tools_config_translation_form_submit(array $form, FormStateInterface $form_state) {
  \Drupal\Core\Cache\Cache::invalidateTags([
    'config:block.block.footertopblock',
  ]);
}
