field.widget.settings.link_target_field_widget:
  type: field.widget.settings.linkit

field.widget.settings.link_target_icon_field_widget:
  type: field.widget.settings.linkit

field.widget.settings.design_field_widget:
  type: mapping
  label: 'Design field widget widget settings'
  mapping:
    size:
      type: integer
      label: 'Size'
    placeholder:
      type: textfield
      label: 'Placeholder'
