<?php

/**
 * @file
 * Contains necessary hooks for Select2 icons.
 */

/**
 * Implements hook_theme().
 */
function select2_icon_theme() {
  return [
    'select2_icon_widget' => [
      'render element' => 'element',
      'preprocess functions' => [
        'template_preprocess_select2_icon',
        'template_preprocess_select',
      ],
    ],
    'select2_icon' => [
      'variables' => [
        'icon_id' => NULL,
        'icon_label' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function select2_icon_form_paragraphs_library_item_edit_form_alter(&$form, &$form_state, $form_id) {
  // Attach select2_icon library to the form library item edit form.
  $form['#attached']['library'][] = 'select2_icon/select2_icon';
}
